-- Таблица для хранения Telegram сообщений
CREATE TABLE IF NOT EXISTS telegram_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id BIGINT NOT NULL,
    chat_id BIGINT NOT NULL,
    chat_title TEXT,
    sender_id BIGINT,
    sender_name TEXT NOT NULL,
    sender_username TEXT,
    text TEXT NOT NULL,
    date TIMESTAMP WITH TIME ZONE NOT NULL,
    ai_analysis JSONB,
    processed BOOLEAN DEFAULT true,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    
    CONSTRAINT unique_message UNIQUE (message_id, chat_id)
);

-- Индексы для быстрого поиска
CREATE INDEX IF NOT EXISTS idx_telegram_messages_chat_id ON telegram_messages(chat_id);
CREATE INDEX IF NOT EXISTS idx_telegram_messages_sender_id ON telegram_messages(sender_id);
CREATE INDEX IF NOT EXISTS idx_telegram_messages_date ON telegram_messages(date DESC);
CREATE INDEX IF NOT EXISTS idx_telegram_messages_ai_analysis ON telegram_messages USING GIN (ai_analysis);

-- RLS политики
ALTER TABLE telegram_messages ENABLE ROW LEVEL SECURITY;

-- Разрешить чтение всем авторизованным
CREATE POLICY "Allow read access for authenticated users"
    ON telegram_messages FOR SELECT
    TO authenticated
    USING (true);

-- Разрешить вставку всем авторизованным
CREATE POLICY "Allow insert for authenticated users"
    ON telegram_messages FOR INSERT
    TO authenticated
    WITH CHECK (true);

-- Функция для автоматического обновления сделок при новых сообщениях
CREATE OR REPLACE FUNCTION handle_new_telegram_message()
RETURNS TRIGGER AS $$
BEGIN
    -- Если AI определил это как заказ, триггер для обновления сделок
    IF NEW.ai_analysis->>'is_order' = 'true' THEN
        -- Логика обновления сделок уже в Python коде
        -- Здесь можно добавить дополнительную логику на SQL уровне
        NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Триггер для вызова функции
CREATE TRIGGER on_telegram_message_insert
    AFTER INSERT ON telegram_messages
    FOR EACH ROW
    EXECUTE FUNCTION handle_new_telegram_message();

-- Вьюха для последних сообщений по клиентам
CREATE OR REPLACE VIEW latest_client_messages AS
SELECT DISTINCT ON (sender_id)
    sender_id,
    sender_name,
    sender_username,
    text,
    date,
    ai_analysis
FROM telegram_messages
WHERE sender_username IS NOT NULL
ORDER BY sender_id, date DESC;
